#!/usr/bin/env bash
# =============================================================================
# Interactive credential configuration for AWS and app secrets.
# Run this once to set up credentials; it will prompt you for values.
# NO credentials are stored in this script.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CREDS_FILE="$PROJECT_ROOT/.env.credentials"
REGION="${AWS_REGION:-ap-south-1}"

echo "=============================================="
echo " Credential Configuration"
echo "=============================================="
echo ""

# 1. AWS credentials
if aws sts get-caller-identity &>/dev/null; then
  ACCOUNT=$(aws sts get-caller-identity --query AccountId --output text)
  echo "AWS credentials OK (account: $ACCOUNT)"
else
  echo "AWS credentials not configured. Running: aws configure"
  echo "You will be prompted for:"
  echo "  - AWS Access Key ID"
  echo "  - AWS Secret Access Key"
  echo "  - Default region (use: $REGION)"
  echo ""
  aws configure
fi

# 2. Collect secrets (user types them; we write to gitignored file)
# Skip prompts if already set in environment
TF_DB_PW="${TF_VAR_db_password:-}"
API_KEY_SECRET="${SSM_API_KEY_SECRET:-}"
JWT_SECRET="${SSM_JWT_SECRET:-}"

if [[ -z "$TF_DB_PW" || -z "$API_KEY_SECRET" || -z "$JWT_SECRET" ]]; then
  echo ""
  echo "Enter application secrets (for .env.credentials - gitignored):"
  echo ""
  [[ -z "$TF_DB_PW" ]] && read -r -p "RDS/DB password (for Terraform TF_VAR_db_password): " TF_DB_PW
  [[ -z "$API_KEY_SECRET" ]] && read -r -p "API_KEY_SECRET (for API validation): " API_KEY_SECRET
  [[ -z "$JWT_SECRET" ]] && read -r -p "JWT_SECRET (for JWT signing): " JWT_SECRET
fi

cat > "$CREDS_FILE" << EOF
# Generated by scripts/configure-credentials.sh - DO NOT COMMIT
# Source this before running: source .env.credentials

# Terraform
export TF_VAR_db_password="$TF_DB_PW"
export ENVIRONMENT=dev

# AWS (optional override; usually from aws configure)
# export AWS_ACCESS_KEY_ID=...
# export AWS_SECRET_ACCESS_KEY=...
# export AWS_REGION=$REGION

# App secrets (for local dev / SSM)
export SSM_API_KEY_SECRET="$API_KEY_SECRET"
export SSM_JWT_SECRET="$JWT_SECRET"
EOF

echo ""
echo "Wrote credentials to: .env.credentials (gitignored)"
echo ""
echo "Next steps:"
echo "  1. source .env.credentials"
echo "  2. ./scripts/aws-setup.sh all"
echo ""
